### ISSUE TITLE
Is France calendar production-ready?

### ISSUE THREAD

**Issue by gilbsgilbs** [novafloss/workalendar#161]
Hi there.

Probably not the best place to ask, but I'm really interrested in integrating this library into a business codebase. I already saw people recommending using it (meaning that they find it suitable for production use already). I was just wondering whether, despite the disclaimer in the README, at least the France calendar was already production-ready in some "simple" cases. Of course, if I encounter any bug, I'd be happy to contribute and I'm not expecting something incredibly stable or well-documented; I just don't want to dive into an early pre-alpha project with dozens of known and unresolved bugs, or with major breaking-changes and refactorings to come. My own business code will be tested thoroughly anyways, and impacts of bugs on this library should be moderate (we'll not pay salaries using this library, nor put hudge load into it. Nobody will be injured in case of trouble :p ).

Just to be clear, the precise question is: this library is some years-old, people seem to already be using it in production with great satisfaction, the project is active and well maintained, I can't find any major issue in the issue tracker, calendars are looking accurate, what makes you say this library is "barely beta"?

Thank you in advance for the enlightenment.
Regards,
Gilbs

**Comment by Natim** [comment]
My take on this would be a YES you can use it for production use.
I would be glad to remove that warning from the README.

**Comment by brunobord** [comment]
I agree, workalendar is ok for production. I haven't witnessed any functional bug so far and we (PeopleDoc) are using it without a problem for years now.
I think I've simply forgot to remove the README warning...

Although, it's not and will never be 100% safe: holidays can change in a snap ; some days are added, or their date is changed, and I don't really know if it's possible to follow every change of every calendar in every country... so it may happen that one available calendar is not accurate, so that's the reason why you have to pay attention to the calendars you'll be using and if you spot any problem with a date, we'll try to ship a bugfix as fast as we can.

Unless unexpected revolutionary events, I'd say that France calendar won't be out-of-sync for a while.

**Comment by brunobord** [comment]
@gilbsgilbs would #162 close this issue?

**Comment by gilbsgilbs** [comment]
Hi!

@brunobord Yes, #162 fixes this issue.

Thank you both for these information. That's exactly what I was expecting. I know calendars are subject to change. World is changing as well. We always have to stay tuned :) .
