### ISSUE TITLE
Germany Saxony Repentence day

### ISSUE THREAD

**Issue by gregn610** [novafloss/workalendar#168]
Wed __before__ 23rd so should be 16th in 2016, not 23rd.
http://www.timeanddate.com/holidays/germany/repentance-day
http://www.qppstudio.net/publicholidays2016/germany.htm
https://en.wikipedia.org/wiki/Public_holidays_in_Germany

**Comment by brunobord** [comment]
As you can expect, I'm on vacation. If somebody in the novafloss org can
take care of this issue and eventually make a bugfix release, that'd be
great.

Le 19 déc. 2016 9:16 PM, "gregn610" <notifications@github.com> a écrit :

Wed *before* 23rd so should be 16th in 2016, not 23rd.
http://www.timeanddate.com/holidays/germany/repentance-day
http://www.qppstudio.net/publicholidays2016/germany.htm
https://en.wikipedia.org/wiki/Public_holidays_in_Germany

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/novafloss/workalendar/issues/168>, or mute the thread

**Comment by Natim** [comment]
See #169

**Comment by Natim** [comment]
Apparently I am set as contributor but I don't have any write permission on this repository nor on Pypi:
